package es.mdef.gaip_libreria.constantes;

public enum AccionesActo {
    AGREGAR_ANFITRIONES,
    AGREGAR_INVITADOS,
    ENVIAR_CORREO_FORMULARIO,
    CONFIGURAR_ZONAS,
    CONFIGURAR_PRIORIDADES,
    CONFIGURAR_DISTRIBUCION,
    BORRAR_ANFITRIONES,
    SENTAR_INVITADOS
}